[target.riscv32imac-unknown-none-elf]
runner = "espflash flash -L defmt"

[env]
DEFMT_LOG="info"

[build]

rustflags = [
  "-C", "link-arg=-Tlinkall.x",
  # Required to obtain backtraces (e.g. when using the "esp-backtrace" crate.)
  # NOTE: May negatively impact performance of produced code
  "-C", "force-frame-pointers",
  # Take a look at https://defmt.ferrous-systems.com/setup
  # To know which linker option to add.
  "-C", "link-arg=-Tdefmt.x",
]

target = "riscv32imac-unknown-none-elf"

[unstable]
build-std = ["core"]
